version: '3.3'
services:
    aesdev:
        image: exp6_aes
        build:
          context: .
          dockerfile: ./Dockerfile
          args:
            - platform='linux/amd64'
            - tag='exp6_aes'
        command: /bin/bash
        volumes:
            - './AES:/home'




            


