version: '3.3'
services:
    aesdev:
        image: aesdev
        build:
          context: .
          dockerfile: ./Dockerfile
          args:
            - platform='linux/amd64'
            - tag='aesdev'
        command: /bin/bash
        volumes:
            - './AES:/home'




            


